/* https://tomeko.net/online_tools/cpp_text_escape.php?lang=en */
char form_str[] = 

"<!DOCTYPE html>\n"
"<html>\n"
"<style>\n"
"input[type=text], input[type=password], select {\n"
"  width: 100%;\n"
"  padding: 12px 20px;\n"
"  margin: 8px 0;\n"
"  display: inline-block;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 4px;\n"
"  box-sizing: border-box;\n"
"  font-size: 60px;\n"
"}\n"
"\n"
"input[type=submit] {\n"
"  width: 100%;\n"
"  background-color: #4CAF50;\n"
"  color: white;\n"
"  padding: 14px 20px;\n"
"  margin: 8px 0;\n"
"  border: none;\n"
"  border-radius: 4px;\n"
"  cursor: pointer;\n"
"  font-size: 60px;\n"
"}\n"
"\n"
"div {\n"
"  border-radius: 5px;\n"
"  background-color: #f2f2f2;\n"
"  padding: 5%;\n"
"  margin: 5%;\n"
"  font-size: 60px\n"
"}\n"
"</style>\n"
"\n"
"<body>\n"
"\n"
"<div>\n"
"  <h3>Connect to your WiFi network</h3>\n"
"  \n"
"  <form action=\"/\" method=\"post\">\n"
"    <label for=\"ssid\">SSID</label>\n"
"    <input type=\"text\" id=\"ssid\" name=\"SSID\" placeholder=\" \">\n"
"    <label for=\"psw\">Password</label>\n"
"    <input type=\"password\" id=\"psw\" name=\"Password\" placeholder=\" \">\n"
"    <input type=\"submit\" value=\"Connect\">\n"
"  </form>\n"
"</div>\n"
"\n"
"</body>\n"
"</html>\n"

;